services:
  site:
    # For local uncomment the following line and comment the image line
    build: .
    #image: ghcr.io/lukeh990/lukeh990.io:release
    container_name: lukeh990-io
    ports:
      - 8080:8080
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 lukeh990-io